name: Code deploy

on:
  workflow_dispatch: # 이 태그가 있으면 workflow를 매뉴얼하게 트리거할 수 있음.
  # push: # push할 때 작동
  #   branches: # 대상이 될 브랜치
  #     - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create SSH Key
        run: | # access key를 actions 내부 워크스페이스에 pem파일로 저장하고 권한을 확보
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/private-key.pem
          chmod 600 ~/private-key.pem
      - name: Create SSH directory # .ssh 디렉토리 생성
        run: | 
          mkdir -p ~/.ssh
      - name: Add known host # known host에 해당 키를 추가
        run: |
          ssh-keyscan ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
      - name: Copy files to remote server # github repo의 모든 파일을 target 경로에 복사함.
        run: |
          cd ${{ github.workspace }}
          scp -i ~/private-key.pem -r ./* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/
          echo "Copied files to remote server"
